// Generated by CoffeeScript 1.10.0

/*
## Foreign function interface
 */
var Ffi, HEAP, HEAP_SIZE, allocator;

HEAP_SIZE = 0x40000;

export const buffer = new ArrayBuffer(HEAP_SIZE);

if (typeof malloc !== "undefined" && malloc !== null) {
  allocator = new malloc.Allocator(buffer);
} else {
  HEAP = new Int32Array(buffer);
  HEAP[0] = 16;
}

Ffi = (function() {
  function Ffi() {}

  Ffi.now = function() {
    return performance.now();
  };


  /*
   * malloc
   *
   * @param nBytes number of bytes required
   * @returns starting offset in the heap
   */

  Ffi.malloc = allocator.alloc;

  Ffi.free = allocator.free;

  return Ffi;

})();

export default Ffi;

export const foreign = Ffi;

export const bufferMax = HEAP_SIZE;
