// Generated by CoffeeScript 1.10.0

/*
 * Run tests
 */
Promise.all(['entity', 'pool'].map(function(x) {
  return System["import"](x);
})).then(function(arg) {
  var entity, pool, ref, ref1;
  (ref = arg[0], entity = ref.entity), (ref1 = arg[1], pool = ref1.pool);
  return describe('Smoke Tests', function() {
    it('Pool', function() {
      return expect(pool).to.not.equal(null);
    });
    it('Entity', function() {
      return expect(entity).to.not.equal(null);
    });
    return it('CreateEntity', function() {
      entity = pool.createEntity();
      return expect(pool.test(entity, 0)).to.equal(1);
    });
  });
}, function(err) {
  return console.log(err);
});
