// Generated by CoffeeScript 1.10.0

/*
 * Run tests
 *
Promise.all(['test1', 'test2', 'test-twister', 'mt19937'].map((x) -> 
  System.import(x))).then ([{test1}, {test2}, {MersenneTwister}, {mt19937}]) ->
 */
Promise.all(['test1', 'test2'].map(function(x) {
  return System["import"](x);
})).then(function(arg) {
  var ref, ref1, test1, test2;
  (ref = arg[0], test1 = ref.test1), (ref1 = arg[1], test2 = ref1.test2);
  return describe('Basic Tests', function() {
    it('Factorial', function() {
      expect(test1.factorial(10)).to.equal(45);
    });
    it('Alloc', function() {
      expect(test1.alloc(10)).to.equal(typeof malloc !== "undefined" && malloc !== null ? 68 : 4);
      expect(test1.alloc(10)).to.equal(typeof malloc !== "undefined" && malloc !== null ? 80 : 14);
    });
    it('List', function() {
      expect(test1.values()).to.equal(typeof malloc !== "undefined" && malloc !== null ? 92 : 24);
      expect(test2.index((typeof malloc !== "undefined" && malloc !== null ? 92 : 24), 2)).to.equal(44);
    });
    return it('And', function() {
      return expect(test2.and(42)).to.equal(42);
    });
  });
}, function(err) {
  return console.log(err);
});
