// Generated by CoffeeScript 1.10.0

/*
## Stdlib
 */
var Stdlib;

Stdlib = (function() {
  function Stdlib() {}

  Stdlib.Math = Math;

  Stdlib.Int8Array = Int8Array;

  Stdlib.Int16Array = Int16Array;

  Stdlib.Int32Array = Int32Array;

  Stdlib.Uint8Array = Uint8Array;

  Stdlib.Uint16Array = Uint16Array;

  Stdlib.Uint32Array = Uint32Array;

  Stdlib.Float32Array = Float32Array;

  Stdlib.Float64Array = Float64Array;

  Stdlib.NaN = NaN;

  Stdlib.Infinity = Infinity;

  return Stdlib;

})();

export default Stdlib;
