// Generated by CoffeeScript 1.10.0
System["import"]('asm').then(function(module) {
  console.log('asm loaded');
  return console.log("asm.getTime = " + (module.asm.getTime()));
}, function(err) {
  return console.log(err);
});
