// Generated by CoffeeScript 1.10.0

/*
## Foreign function interface
 */
var Ffi, HEAP;

Ffi = (function() {
  function Ffi() {}

  Ffi.now = function() {
    return performance.now();
  };


  /*
   * malloc
   *
   * @param nBytes number of bytes required
   * @returns starting offset in the heap
   */

  Ffi.malloc = function(nBytes) {
    var offset;
    offset = HEAP[0];
    HEAP[0] = offset + nBytes;
    return offset;
  };

  return Ffi;

})();

export default Ffi;

export const buffer = new ArrayBuffer(0x40000);

HEAP = new Int32Array(buffer);

HEAP[0] = 16;
