// Generated by CoffeeScript 1.10.0

/*
## Foreign function interface
 */
var Ffi, HEAP;

Ffi = (function() {
  function Ffi() {}

  Ffi.now = function() {
    return performance.now();
  };

  Ffi.malloc = function(n) {
    var m;
    m = HEAP[0];
    HEAP[0] = m + n;
    return m;
  };

  return Ffi;

})();

export default Ffi;

export const buffer = new ArrayBuffer(0x40000);

HEAP = new Int32Array(buffer);

HEAP[0] = 16;
