// Generated by CoffeeScript 1.10.0
System["import"]('asm').then(function(module) {
  var elapsed;
  console.log('asm loaded');
  elapsed = module.asm.getTime();
  console.log("asm.getTime = " + elapsed);
  console.log("Compile", elapsed < 200 ? "Ok" : "ERROR");
  console.log(module.asm.test_malloc(16));
  return console.log(module.asm.test_malloc(16));
}, function(err) {
  return console.log(err);
});

System["import"]('mt19937').then(function(module) {
  console.log('mt19937 loaded');
  console.log(module.mt19937.genrand_int32());
  console.log(module.mt19937.genrand_int32());
  console.log(module.mt19937.genrand_int32());
  return console.log(module.mt19937.genrand_int32());
}, function(err) {
  return console.log(err);
});
