// Generated by CoffeeScript 1.10.0

/*
## Foreign function interface
 */
var Ffi;

Ffi = (function() {
  function Ffi() {}

  Ffi.now = function() {
    return performance.now();
  };

  return Ffi;

})();

export default Ffi;
