#!/usr/bin/env coffee
###
 * dē-ish compiler
 * 
 * usage:
 *      node ./src/dish.js test/test.d -m -w --output test/test.js
 * 
###
'use strict'
fs = require('fs')
path = require('path')
util = require("util")
{args, flags} = require('./args')
lexer = require('./lexer')
parser = require('./parser')
escodegen = require('escodegen')
esprima = require('esprima')
esmangle = require('esmangle')
liquid = require('liquid.coffee')
manifest = require('../package.json')

usage = """
Usage: dish <filename>
    -o --output        output file name
    -t --template      template file name
    -m --mangle        mangle output
    -w --whitespace    remove whitespace
"""

if args.count<3 
    console.log usage
    process.exit 1

source      = args()
template    = args  '-t', '--template', './src/asm.tpl.js'
output      = args  '-o', '--output'
mangle      = flags '-m', '--mangle'
whitespace  = flags '-w', '--whitespace'

console.log "*** dish #{manifest.version} ***"
console.log "*** #{source} ***"

parsed = parser.parse(lexer(fs.readFileSync(source, 'utf8')), mangle)

## todo: fix this bug
parsed.heapi8 = true
parsed.heapu8 = true
parsed.heapi16 = true
parsed.heapu16 = true
parsed.heapi32 = true
parsed.heapu32 = true
parsed.heapf32 = true
parsed.heapf64 = true


tpl = liquid.Template.parse(fs.readFileSync(template, 'utf8'))

code = escodegen.generate(parsed.ast, verbatim: 'verbatim')
    # .replace(/\('0.0'\)/g, '0.0') # reverse verbatim option

out = tpl.render
    name:       parsed.name
    version:    manifest.version
    source:     source
    code:       code
    heapsize:   0x4000
    exports:    parsed.exports
    float:      parsed.float
    heapi8:     parsed.heapi8
    heapu8:     parsed.heapu8
    heapi16:    parsed.heapi16
    heapu16:    parsed.heapu16
    heapi32:    parsed.heapi32
    heapu32:    parsed.heapu32
    heapf32:    parsed.heapf32
    heapf64:    parsed.heapf64
    malloc:     parsed.malloc

###
 * Fix Ups
###
out = out.replace(/\n\n/mg, '\n') while /\n\n/.test(out)    # fix-up empty lines
out = out.replace(/__double__/mg, '')                       # fix-up type conversions
out = out.replace(/__int__/mg, '~~')                        # fix-up type conversions
out = out.replace(/\+fround/mg, 'fround')                   # fix-up type conversions
hdr = "/** generated by dish #{manifest.version} */\n"
if mangle
    i = out.indexOf(parsed.name)
    if i>0 
        lhs = out.substr(0,i)
        rhs = out.substr(i)
        ast = esprima.parse(rhs)
        res = esmangle.mangle(ast)
        out = lhs+escodegen.generate(res, format: compact: whitespace)
            .replace(/'0.0'/g, '0.0')               # reverse verbatim option
    else out = out.replace(/\('0.0'\)/g, '0.0')     # reverse verbatim option
else out = out.replace(/\('0.0'\)/g, '0.0')         # reverse verbatim option


if output then fs.writeFileSync output, hdr+out
else console.log out



